name: Linting and Formating
on: push
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Run linter
        run: npm run lint
      - name: Run format checking
        run: npm run check
